### ISSUE TITLE
Login work flow !

### ISSUE THREAD

**Issue by whyorean** [whyorean/playstore-api-v2#1]
Due to recent changes on Google side, the login flow has changed a bit.

This api no longer support a login by <email,passwird> pair, the current flow is as follws:

1. Get oauthToken from https://accounts.google.com/EmbeddedSetup/
2. Get [aasToken](https://github.com/whyorean/playstore-api-v2/blob/master/src/main/java/com/dragons/aurora/playstoreapiv2/GooglePlayAPI.java#L302) using the <email,oauthToken> 
3. Get [authToken](https://github.com/whyorean/playstore-api-v2/blob/master/src/main/java/com/dragons/aurora/playstoreapiv2/GooglePlayAPI.java#L275) using <email,aasToken>
4. Finally you get authToken, you can use this authToken to make further transactions.

Why this changes ?
Previous login method started asking for CAPTCHAs, although I was able to get the captchatoken and captchaimage, but post solving the captcha how I was supposed to send it bask and get authToken was unknown, I tried various methods but failed. Solving captchas and testing new params is very tedious.

So I started looking for new methods, with help of @arbu I was able to adapt to the way microg manages to get authTokens.

However I'm still unsure about the CAPTCHA issue and the solution to it, I gave up !
But old login method works for Python3, NodeJS 8, I dont know how and why, more details are covered by @hoffie [here](https://gitlab.com/AuroraOSS/AuroraStore/issues/217) citing some TLS Connection Finferprinting, I dont understand that language, my bad !

**Comment by whyorean** [comment]
Here is a simple Python3 code to directly get aasToken from email & password

```
def get_aac_token(email, password):
    token_param = 'Token'
    enc_password = utils.encrypt_password(email, password)
    params = {'Email': email,
              'EncryptedPasswd': enc_password,
              'add_account': '1',
              'accountType': 'HOSTED_OR_GOOGLE',
              'google_play_services_version': '11951438',
              'has_permission': '1', 
              'source': 'android',
              'device_country': 'de',
              'lang': 'de',
              'client_sig': '38918a453d07199354f8b19af05ec6562ced5788',
              'callerSig': '38918a453d07199354f8b19af05ec6562ced5788',
              'service': 'sj',
              'callerPkg': 'com.google.android.gms'}

    raw_response = requests.post(constants.AUTH_URL, data=params)

    if raw_response.status_code >=400:
        print(raw_response.text.split())

    if raw_response.status_code == 200:
        response = raw_response.text.split()
        for param in response:
            if param.startswith(token_param):
                print(email, param[6:])
                return email, param[6:]
    else:
        return None, None
```

**Comment by whyorean** [comment]
Here is a sample android app to demonstrate the same : [Authenticator](https://github.com/whyorean/Authenticator)

**Comment by hunfwj** [comment]
I have a question,I don't Know how to refresh authToken, it will expire

**Comment by hunfwj** [comment]
I use Java and use your code , but oauthToken is 
Manual acquisition.if authToken is expire,that is bad.
And I don't spider google Login page,my bad!!!

**Comment by hunfwj** [comment]
Do you have good any way ? I will thank you very much

**Comment by whyorean** [comment]
> Do you have good any way ? I will thank you very much

You can get authToken from AASToken & Email using the following [code snippet](https://github.com/whyorean/playstore-api-v2/blob/master/src/main/java/com/dragons/aurora/playstoreapiv2/GooglePlayAPI.java#L275).

**Comment by whyorean** [comment]
> I have a question,I don't Know how to refresh authToken, it will expire

You can't refresh auth token rather you generate new auth token

**Comment by hunfwj** [comment]
assToken is not expire ?  I will do it , use your way. thank you ,you are pretty good。

**Comment by kar** [comment]
@whyorean could you describe the current way of getting the tokens a bit more? The README is not up to date, and I'm not sure what to do after I've setup the oauth credentials using google console (I have the client ID and secret).

**Comment by whyorean** [comment]
> @whyorean could you describe the current way of getting the tokens a bit more? The README is not up to date, and I'm not sure what to do after I've setup the oauth credentials using google console (I have the client ID and secret).

Yes yes, will update the README, meanwhile you can follow up this issue, for the same.

**Comment by kar** [comment]
@whyorean I've tried, for me that embedded setup page spins forever after I enter my credentials and accept the terms. Any clue?

**Comment by kar** [comment]
@whyorean is the token dispenser still a viable option considering those login changes?

**Comment by whyorean** [comment]
> @whyorean I've tried, for me that embedded setup page spins forever after I enter my credentials and accept the terms. Any clue?

Let it spin it doesn't matter, you will get your aas token from cookie, also I have written  a sample demonstration [app](https://github.com/whyorean/Authenticator) have a look at it. 

In case you use python have  a look at [this](https://github.com/whyorean/ASSTokenGrabber).

> @whyorean is the token dispenser still a viable option considering those login changes?

Yes indeed, all I do is use `AAS Tokens` instead of passwords to generate `Auth Tokens`

**Comment by Teketel** [comment]
> Here is a simple Python3 code to directly get aasToken from email & password
> 
> ```
> def get_aac_token(email, password):
>     token_param = 'Token'
>     enc_password = utils.encrypt_password(email, password)
>     params = {'Email': email,
>               'EncryptedPasswd': enc_password,
>               'add_account': '1',
>               'accountType': 'HOSTED_OR_GOOGLE',
>               'google_play_services_version': '11951438',
>               'has_permission': '1', 
>               'source': 'android',
>               'device_country': 'de',
>               'lang': 'de',
>               'client_sig': '38918a453d07199354f8b19af05ec6562ced5788',
>               'callerSig': '38918a453d07199354f8b19af05ec6562ced5788',
>               'service': 'sj',
>               'callerPkg': 'com.google.android.gms'}
> 
>     raw_response = requests.post(constants.AUTH_URL, data=params)
> 
>     if raw_response.status_code >=400:
>         print(raw_response.text.split())
> 
>     if raw_response.status_code == 200:
>         response = raw_response.text.split()
>         for param in response:
>             if param.startswith(token_param):
>                 print(email, param[6:])
>                 return email, param[6:]
>     else:
>         return None, None
> ```

Is it possible to implement this with JAVA?

**Comment by matlink** [comment]
@whyorean can you post the whole python script? I don't have details like the way the password is encrypted and the AUTH_URL.

**Comment by shishKabab846** [comment]
@whyorean @kar 
I'm using [Google Sign In](https://developers.google.com/identity/sign-in/android/start-integrating)
I configured the app and got the `client_id` and the `client_secret` what should I do with them?

I'm able to sign in with the emails that this Google Sign In Api found, but when I'm trying to get the AAS Token, I'm getting an exception (Auth Exception 403 Bad Authentication) 

any suggestions, in case I want to use this sign in button instead of using the webview?

**Comment by konsumer** [comment]
@whyorean in your python snippet, what is `utils.encrypt_password` and `constants.AUTH_URL`?

**Comment by whyorean** [comment]
> @whyorean in your python snippet, what is `utils.encrypt_password` and `constants.AUTH_URL`?

Have a look [here](https://github.com/whyorean/AASTokenGrabber)

**Comment by konsumer** [comment]
@whyorean thanks! works great. Do you have any more info about it? I'd like to implement `utils.encrypt_password` in JS, but I'm not sure where to start. Is there a ready-made node-library that does this?

**Comment by whyorean** [comment]
> @whyorean thanks! works great. Do you have any more info about it? I'd like to implement `utils.encrypt_password` in JS, but I'm not sure where to start. Is there a ready-made node-library that does this?

I'm not sure about JS, but I believe there already exist some NodeJS adaptations of the same.
Have a look at this [repo](https://github.com/dweinstein/node-google-play)
