### ISSUE TITLE
Protobuf issue

### ISSUE THREAD

**Issue by MagisG** [whyorean/playstore-api-v2#2]
I got this kind of error when I add this lib as dependencie:

implementation "androidx.security:security-crypto:1.0.0-alpha02"

Duplicate class com.google.protobuf.AbstractMessageLite found in modules playstore-api-v2-2.4.jar (com.github.whyorean:playstore-api-v2:2.4) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)

Duplicate class com.google.protobuf.AbstractMessageLite$Builder found in modules playstore-api-v2-2.4.jar (com.github.whyorean:playstore-api-v2:2.4) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)

etc.....

**Comment by whyorean** [comment]
Use it the following way :

`implementation("androidx.security:security-crypto:1.0.0-alpha02") {
    exclude module: "TheModuleNameCausingConflict"
}`
