### ISSUE TITLE
Add WearOS and AndoidGo device configs

### ISSUE THREAD

**Issue by whyorean** [whyorean/playstore-api-v2#3]

**Comment by LuggyLuke** [comment]
For what its worth, Here is my ticwatch e config: 

`UserReadableName = Ticwatch E
Build.HARDWARE = mooneye
Build.RADIO = 976_GEN_PACK-1.103654.1.105572.1,976_GEN_PACK-1.103654.1.105572.1
Build.BOOTLOADER = mooneye0.5.30.0.0.5
Build.FINGERPRINT = mobvoi/mooneye/mooneye:8.0.0/OWDR.180307.020/5000261:user/release-keys
Build.BRAND = mobvoi
Build.DEVICE = mooneye
Build.VERSION.SDK_INT = 26
Build.MODEL = Ticwatch E
Build.MANUFACTURER = Mobvoi
Build.PRODUCT = mooneye
Build.ID = OWDR.180307.020
Build.VERSION.RELEASE = 8.0.0
TouchScreen = 3
Keyboard = 1
Navigation = 1
ScreenLayout = 1
HasHardKeyboard = false
HasFiveWayNavigation = false
GL.Version = 131072
Screen.Density = 280
Screen.Width = 400
Screen.Height = 400
Platforms = armeabi-v7a,armeabi
SharedLibraries = clockwork-system,android.ext.services,android.ext.shared,android.test.runner,com.android.future.usb.accessory,com.android.location.provider,com.google.android.gms,com.google.android.wearable,javax.obex,org.apache.http.legacy
Features = android.hardware.audio.output,android.hardware.bluetooth,android.hardware.bluetooth_le,android.hardware.faketouch,android.hardware.location,android.hardware.location.gps,android.hardware.microphone,android.hardware.screen.portrait,android.hardware.sensor.accelerometer,android.hardware.sensor.compass,android.hardware.sensor.gyroscope,android.hardware.sensor.heartrate,android.hardware.sensor.stepcounter,android.hardware.sensor.stepdetector,android.hardware.touchscreen,android.hardware.touchscreen.multitouch,android.hardware.type.watch,android.hardware.usb.accessory,android.hardware.wifi,android.software.activities_on_secondary_displays,android.software.connectionservice,android.software.cts,android.software.device_admin,android.software.home_screen,android.software.input_methods,android.software.live_wallpaper,android.software.voice_recognizers,com.google.wearable.hardware.sensor.heartrate.fitness,oem.tw.hardware.ticwatch
Locales = ar,ar_SA,ast,be,be_BY,bg,bg_BG,bh_IN,ca,ca_ES,cs,cy_GB,da,da_DK,de,de_DE,el,el_GR,en,en_GB,en_US,en_XA,es,es_ES,es_US,et,et_EE,fi,fi_FI,fr,fr_CA,fr_FR,gl,gl_ES,hi,hi_IN,hr,hr_HR,hu,hu_HU,in,in_ID,it,it_IT,iw,iw_IL,ja,ja_JP,kab_DZ,ko,ko_KR,lt,lt_LT,nb,nb_NO,nl,nl_BE,nl_NL,pa,pa_IN,pl,pl_PL,pt,pt_BR,pt_PT,ro,ro_RO,ru,ru_RU,sc_IT,sk,sk_SK,sr,sv,sv_SE,th,th_TH,tr,tr_TR,uk,uk_UA,vi,vi_VN,zh_CN,zh_HK,zh_TW
GSF.version = 201516070
Vending.version = 81932605
Vending.versionString = 19.3.26-all [5] [PR] 301645536
CellOperator = 26203
SimOperator = 26207
TimeZone = Europe/Berlin
GL.Extensions = GL_ARM_mali_program_binary,GL_ARM_mali_shader_binary,GL_ARM_rgba8,GL_EXT_blend_minmax,GL_EXT_debug_marker,GL_EXT_discard_framebuffer,GL_EXT_multisampled_render_to_texture,GL_EXT_robustness,GL_EXT_shader_texture_lod,GL_EXT_texture_format_BGRA8888,GL_KHR_debug,GL_OES_EGL_image,GL_OES_EGL_image_external,GL_OES_EGL_sync,GL_OES_byte_coordinates,GL_OES_compressed_ETC1_RGB8_texture,GL_OES_compressed_paletted_texture,GL_OES_depth24,GL_OES_depth_texture,GL_OES_depth_texture_cube_map,GL_OES_draw_texture,GL_OES_extended_matrix_palette,GL_OES_fixed_point,GL_OES_framebuffer_object,GL_OES_get_program_binary,GL_OES_matrix_get,GL_OES_matrix_palette,GL_OES_packed_depth_stencil,GL_OES_point_size_array,GL_OES_point_sprite,GL_OES_query_matrix,GL_OES_read_format,GL_OES_rgb8_rgba8,GL_OES_single_precision,GL_OES_standard_derivatives,GL_OES_stencil8,GL_OES_texture_cube_map,GL_OES_texture_npot,GL_OES_vertex_half_float
Roaming = mobile-notroaming
Client = android-google`

**Comment by whyorean** [comment]
v2 is now deprecated, added in v3 [here](https://gitlab.com/AuroraOSS/gplayapi/-/commit/eca8e56a47ff155c802094ec13eadc1232e4350e)
