### ISSUE TITLE
version 2.5 build failed

### ISSUE THREAD

**Issue by zhangmiaoCHN** [whyorean/playstore-api-v2#5]
hello, in latest version 2.5, where i run `gradlew :assemble`, some errors occurred.

it seems like `src/main/proto/GooglePlay.proto` added class `searchSuggestResponse` repeatedly

```
message searchSuggestResponse {
}
```

**Comment by whyorean** [comment]
You can get the latest binaries from [JitPack](https://jitpack.io/#whyorean/playstore-api-v2/2.5)
